name: NodeJS CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
    types: 
      - closed
  
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre-install
      run: |
        npm install
    - name: Lint
      run: |
        npm run lint


  build:
    # if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre-install
      run: |
        npm run prestart
